# Generated by Django 5.2.9 on 2026-01-22 03:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Categoría Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EntradaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Número de factura del proveedor', max_length=50, verbose_name='Número de Factura de Compra')),
                ('fecha_compra', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Compra')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total (C$)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_compra', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
            ],
            options={
                'verbose_name': 'Entrada/Compra',
                'verbose_name_plural': 'Entradas/Compras',
                'ordering': ['-fecha_compra', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NombreProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único del producto (ej: Arroz, Azúcar, etc.)', max_length=200, unique=True, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción general del producto', null=True, verbose_name='Descripción General')),
                ('unidad_medida', models.CharField(default='unidad', help_text='Ej: unidad, kg, litro, caja, etc.', max_length=20, verbose_name='Unidad de Medida')),
                ('activo', models.BooleanField(default=True, help_text='Si está inactivo, no se podrá usar en nuevos productos', verbose_name='Nombre Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece este producto', on_delete=django.db.models.deletion.PROTECT, related_name='nombres_productos', to='inventario.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Nombre de Producto',
                'verbose_name_plural': 'Nombres de Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del producto (SKU, código de barras, etc.)', max_length=50, unique=True, verbose_name='Código del Producto')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción específica de esta instancia del producto (opcional)', null=True, verbose_name='Descripción Específica')),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio en Córdobas Nicaragüenses', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Venta (C$)')),
                ('precio_compra', models.DecimalField(decimal_places=2, help_text='Precio de compra en Córdobas Nicaragüenses', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Compra (C$)')),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0, help_text='Costo promedio calculado automáticamente basado en todas las compras', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Promedio (C$)')),
                ('porcentaje_ganancia', models.DecimalField(decimal_places=2, default=30.0, help_text='Porcentaje de ganancia para calcular precio de venta automáticamente', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje de Ganancia (%)')),
                ('actualizar_precio_automatico', models.BooleanField(default=True, help_text='Si está activo, el precio de venta se actualiza automáticamente al calcular el costo promedio', verbose_name='Actualizar Precio Automáticamente')),
                ('stock_actual', models.IntegerField(default=0, help_text='Cantidad disponible en inventario', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Actual')),
                ('stock_minimo', models.IntegerField(default=0, help_text='Cantidad mínima antes de alertar', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Mínimo')),
                ('unidades_por_paquete', models.IntegerField(default=1, help_text='Ej: Si compra una caja de 24 unidades, ponga 24. Si vende por unidad individual, ponga 1.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Unidades por Paquete/Caja')),
                ('fecha_expiracion', models.DateField(blank=True, help_text='Fecha de expiración del producto (opcional)', null=True, verbose_name='Fecha de Expiración')),
                ('activo', models.BooleanField(default=True, verbose_name='Producto Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('categoria', models.ForeignKey(help_text='Categoría del producto (heredada del nombre de producto)', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria', verbose_name='Categoría')),
                ('nombre_producto', models.ForeignKey(help_text='Nombre del producto del catálogo', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.nombreproducto', verbose_name='Nombre del Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre_producto__nombre', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEntradaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario (C$)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal (C$)')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento del Lote')),
                ('entrada_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.entradacompra', verbose_name='Entrada/Compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_compra', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Entrada/Compra',
                'verbose_name_plural': 'Detalles de Entradas/Compras',
            },
        ),
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ajuste', models.CharField(choices=[('AUMENTO', 'Aumento (+)'), ('DISMINUCION', 'Disminución (-)')], max_length=20, verbose_name='Tipo de Ajuste')),
                ('motivo', models.CharField(choices=[('INVENTARIO_INICIAL', 'Inventario Inicial'), ('CORRECCION', 'Corrección de Error'), ('ROTURA', 'Merma por Rotura/Daño'), ('VENCIMIENTO', 'Merma por Vencimiento'), ('ROBO', 'Merma por Robo/Pérdida'), ('CONSUMO', 'Consumo Interno'), ('OTRO', 'Otro Motivo')], default='CORRECCION', max_length=30, verbose_name='Motivo del Ajuste')),
                ('cantidad_anterior', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Anterior')),
                ('cantidad_nueva', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Nueva (Física Real)')),
                ('diferencia', models.IntegerField(help_text='Diferencia calculada automáticamente', verbose_name='Diferencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones adicionales')),
                ('fecha_ajuste', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Ajuste')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_inventario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ajuste de Inventario',
                'verbose_name_plural': 'Ajustes de Inventario',
                'ordering': ['-fecha_ajuste', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Proveedor')),
                ('ruc', models.CharField(blank=True, help_text='Número de RUC (opcional)', max_length=20, null=True, verbose_name='RUC')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=17, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='Proveedor Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='inventario__nombre_70461d_idx'), models.Index(fields=['activo'], name='inventario__activo_f76b65_idx')],
            },
        ),
        migrations.AddField(
            model_name='entradacompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='inventario.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddIndex(
            model_name='nombreproducto',
            index=models.Index(fields=['nombre'], name='inventario__nombre_28a3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='nombreproducto',
            index=models.Index(fields=['categoria'], name='inventario__categor_ff9c97_idx'),
        ),
        migrations.AddIndex(
            model_name='nombreproducto',
            index=models.Index(fields=['activo'], name='inventario__activo_a199f9_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo'], name='inventario__codigo_d18360_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='inventario__categor_32aa4f_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='inventario__activo_041dee_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['fecha_expiracion'], name='inventario__fecha_e_3a5aec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleentradacompra',
            unique_together={('entrada_compra', 'producto')},
        ),
    ]
