# Generated by Django 5.2.9 on 2026-01-06 02:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Categoría Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EntradaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Número de factura del proveedor', max_length=50, verbose_name='Número de Factura de Compra')),
                ('proveedor', models.CharField(max_length=200, verbose_name='Proveedor')),
                ('fecha_compra', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Compra')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total (C$)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_compra', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
            ],
            options={
                'verbose_name': 'Entrada/Compra',
                'verbose_name_plural': 'Entradas/Compras',
                'ordering': ['-fecha_compra', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del producto (SKU, código de barras, etc.)', max_length=50, unique=True, verbose_name='Código del Producto')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio en Córdobas Nicaragüenses', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Venta (C$)')),
                ('precio_compra', models.DecimalField(decimal_places=2, help_text='Precio de compra en Córdobas Nicaragüenses', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Compra (C$)')),
                ('stock_actual', models.IntegerField(default=0, help_text='Cantidad disponible en inventario', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Actual')),
                ('stock_minimo', models.IntegerField(default=0, help_text='Cantidad mínima antes de alertar', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Mínimo')),
                ('unidad_medida', models.CharField(default='unidad', help_text='Ej: unidad, kg, litro, caja, etc.', max_length=20, verbose_name='Unidad de Medida')),
                ('activo', models.BooleanField(default=True, verbose_name='Producto Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEntradaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario (C$)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal (C$)')),
                ('entrada_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.entradacompra', verbose_name='Entrada/Compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_compra', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Entrada/Compra',
                'verbose_name_plural': 'Detalles de Entradas/Compras',
            },
        ),
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ajuste', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('CORRECCION', 'Corrección')], max_length=20, verbose_name='Tipo de Ajuste')),
                ('cantidad_anterior', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Anterior')),
                ('cantidad_nueva', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Nueva')),
                ('diferencia', models.IntegerField(help_text='Diferencia calculada automáticamente', verbose_name='Diferencia')),
                ('motivo', models.TextField(verbose_name='Motivo del Ajuste')),
                ('fecha_ajuste', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Ajuste')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_inventario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ajuste de Inventario',
                'verbose_name_plural': 'Ajustes de Inventario',
                'ordering': ['-fecha_ajuste', '-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo'], name='inventario__codigo_d18360_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='inventario__categor_32aa4f_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='inventario__activo_041dee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleentradacompra',
            unique_together={('entrada_compra', 'producto')},
        ),
    ]
