# Generated by Django 5.2.9 on 2026-01-10 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='actualizar_precio_automatico',
            field=models.BooleanField(default=True, help_text='Si está activo, el precio de venta se actualiza automáticamente al calcular el costo promedio', verbose_name='Actualizar Precio Automáticamente'),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo promedio calculado automáticamente basado en todas las compras', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Promedio (C$)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentaje_ganancia',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Porcentaje de ganancia para calcular precio de venta automáticamente', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje de Ganancia (%)'),
        ),
    ]
