# Generated by Django 5.2.9 on 2026-01-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajusteinventario',
            name='motivo',
            field=models.CharField(max_length=100, verbose_name='Motivo del Ajuste'),
        ),
        migrations.AlterField(
            model_name='ajusteinventario',
            name='tipo_ajuste',
            field=models.CharField(choices=[('ENTRADA', 'Entrada (+)'), ('SALIDA', 'Salida (-)')], max_length=20, verbose_name='Tipo de Ajuste'),
        ),
    ]
