# Generated by Django 5.2.9 on 2026-01-10 02:42

import django.db.models.deletion
from django.db import migrations, models


def migrar_nombres_productos(apps, schema_editor):
    """
    Migración de datos: crear NombreProducto a partir de los productos existentes
    """
    Producto = apps.get_model('inventario', 'Producto')
    NombreProducto = apps.get_model('inventario', 'NombreProducto')
    Categoria = apps.get_model('inventario', 'Categoria')
    
    # Obtener todos los productos únicos por nombre
    productos = Producto.objects.all()
    nombres_creados = {}
    
    for producto in productos:
        nombre = producto.nombre if hasattr(producto, 'nombre') else None
        unidad = producto.unidad_medida if hasattr(producto, 'unidad_medida') else 'unidad'
        categoria = producto.categoria
        
        if nombre and nombre not in nombres_creados:
            # Crear NombreProducto si no existe
            nombre_producto, created = NombreProducto.objects.get_or_create(
                nombre=nombre,
                defaults={
                    'categoria': categoria,
                    'unidad_medida': unidad,
                    'descripcion': producto.descripcion if hasattr(producto, 'descripcion') else '',
                    'activo': True
                }
            )
            nombres_creados[nombre] = nombre_producto
        
        # Asignar el nombre_producto al producto
        if nombre and nombre in nombres_creados:
            producto.nombre_producto = nombres_creados[nombre]
            producto.save()


def revertir_migracion(apps, schema_editor):
    """
    Revertir la migración (no se puede hacer completamente)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_actualizar_precio_automatico_and_more'),
    ]

    operations = [
        # Primero crear el modelo NombreProducto
        migrations.CreateModel(
            name='NombreProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único del producto (ej: Arroz, Azúcar, etc.)', max_length=200, unique=True, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción general del producto', null=True, verbose_name='Descripción General')),
                ('unidad_medida', models.CharField(default='unidad', help_text='Ej: unidad, kg, litro, caja, etc.', max_length=20, verbose_name='Unidad de Medida')),
                ('activo', models.BooleanField(default=True, help_text='Si está inactivo, no se podrá usar en nuevos productos', verbose_name='Nombre Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece este producto', on_delete=django.db.models.deletion.PROTECT, related_name='nombres_productos', to='inventario.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Nombre de Producto',
                'verbose_name_plural': 'Nombres de Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='nombreproducto',
            index=models.Index(fields=['nombre'], name='inventario__nombre_28a3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='nombreproducto',
            index=models.Index(fields=['categoria'], name='inventario__categor_ff9c97_idx'),
        ),
        migrations.AddIndex(
            model_name='nombreproducto',
            index=models.Index(fields=['activo'], name='inventario__activo_a199f9_idx'),
        ),
        # Agregar el campo nombre_producto como nullable
        migrations.AddField(
            model_name='producto',
            name='nombre_producto',
            field=models.ForeignKey(blank=True, help_text='Nombre del producto del catálogo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.nombreproducto', verbose_name='Nombre del Producto'),
        ),
        # Migrar los datos
        migrations.RunPython(migrar_nombres_productos, revertir_migracion),
        # Ahora eliminar los campos antiguos
        migrations.RemoveField(
            model_name='producto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_medida',
        ),
        # Hacer nombre_producto requerido
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.ForeignKey(help_text='Nombre del producto del catálogo', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.nombreproducto', verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(help_text='Categoría del producto (heredada del nombre de producto)', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción específica de esta instancia del producto (opcional)', null=True, verbose_name='Descripción Específica'),
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre_producto__nombre', 'codigo'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
