# Generated by Django 5.2.9 on 2026-01-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_ajusteinventario_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajusteinventario',
            name='motivo',
            field=models.CharField(choices=[('INVENTARIO_INICIAL', 'Inventario Inicial'), ('CORRECCION', 'Corrección de Error'), ('ROTURA', 'Merma por Rotura/Daño'), ('VENCIMIENTO', 'Merma por Vencimiento'), ('ROBO', 'Merma por Robo/Pérdida'), ('CONSUMO', 'Consumo Interno'), ('VENTA', 'Venta'), ('ANULACION', 'Anulación de Venta'), ('OTRO', 'Otro Motivo')], default='CORRECCION', max_length=100, verbose_name='Motivo del Ajuste'),
        ),
    ]
