# Generated by Django 5.2.9 on 2026-01-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_crear_nombre_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_expiracion',
            field=models.DateField(blank=True, help_text='Fecha de expiración del producto (opcional)', null=True, verbose_name='Fecha de Expiración'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['fecha_expiracion'], name='inventario__fecha_e_3a5aec_idx'),
        ),
    ]
