# Generated by Django 5.2.9 on 2026-01-22 03:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_producto_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteinventario',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones adicionales'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidades_por_paquete',
            field=models.IntegerField(default=1, help_text='Ej: Si compra una caja de 24 unidades, ponga 24. Si vende por unidad individual, ponga 1.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Unidades por Paquete/Caja'),
        ),
        migrations.AlterField(
            model_name='ajusteinventario',
            name='cantidad_nueva',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Nueva (Física Real)'),
        ),
        migrations.AlterField(
            model_name='ajusteinventario',
            name='motivo',
            field=models.CharField(choices=[('INVENTARIO_INICIAL', 'Inventario Inicial'), ('CORRECCION', 'Corrección de Error'), ('ROTURA', 'Merma por Rotura/Daño'), ('VENCIMIENTO', 'Merma por Vencimiento'), ('ROBO', 'Merma por Robo/Pérdida'), ('CONSUMO', 'Consumo Interno'), ('OTRO', 'Otro Motivo')], default='CORRECCION', max_length=30, verbose_name='Motivo del Ajuste'),
        ),
        migrations.AlterField(
            model_name='ajusteinventario',
            name='tipo_ajuste',
            field=models.CharField(choices=[('AUMENTO', 'Aumento (+)'), ('DISMINUCION', 'Disminución (-)')], max_length=20, verbose_name='Tipo de Ajuste'),
        ),
    ]
