# Generated by Django 5.2.9 on 2026-01-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_ajusteinventario_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleentradacompra',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento del Lote'),
        ),
    ]
