# Generated by Django 5.2.9 on 2026-01-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_detalleentradacompra_fecha_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Proveedor')),
                ('ruc', models.CharField(blank=True, help_text='Número de RUC (opcional)', max_length=20, null=True, verbose_name='RUC')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=17, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='Proveedor Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='inventario__nombre_70461d_idx'), models.Index(fields=['activo'], name='inventario__activo_f76b65_idx')],
            },
        ),
    ]
