# Generated by Django 5.2.9 on 2026-01-22 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradacompra',
            name='proveedor_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='inventario.proveedor', verbose_name='Proveedor (Nuevo)'),
        ),
    ]
