# Generated by Django 5.2.9 on 2026-01-22 03:31

from django.db import migrations


def migrar_proveedores(apps, schema_editor):
    EntradaCompra = apps.get_model('inventario', 'EntradaCompra')
    Proveedor = apps.get_model('inventario', 'Proveedor')
    
    for entrada in EntradaCompra.objects.all():
        if entrada.proveedor:
            proveedor, created = Proveedor.objects.get_or_create(nombre=entrada.proveedor)
            entrada.proveedor_fk = proveedor
            entrada.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_entradacompra_proveedor_fk'),
    ]

    operations = [
        migrations.RunPython(migrar_proveedores),
    ]
