# Generated by Django 5.2.9 on 2026-01-22 03:33

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_migrar_proveedores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradacompra',
            name='proveedor',
        ),
        migrations.RenameField(
            model_name='entradacompra',
            old_name='proveedor_fk',
            new_name='proveedor',
        ),
        migrations.AlterField(
            model_name='entradacompra',
            name='proveedor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='compras',
                to='inventario.proveedor',
                verbose_name='Proveedor'
            ),
        ),
    ]
