# Generated by Django 5.2.9 on 2026-01-06 02:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('cedula', models.CharField(blank=True, help_text='Cédula de identidad (opcional)', max_length=20, null=True, verbose_name='Cédula')),
                ('telefono', models.CharField(blank=True, max_length=17, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('tipo_cliente', models.CharField(choices=[('REGULAR', 'Cliente Regular'), ('FRECUENTE', 'Cliente Frecuente'), ('MAYORISTA', 'Cliente Mayorista')], default='REGULAR', max_length=20, verbose_name='Tipo de Cliente')),
                ('activo', models.BooleanField(default=True, verbose_name='Cliente Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['cedula'], name='ventas_clie_cedula_6893d0_idx'), models.Index(fields=['activo'], name='ventas_clie_activo_136eb3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Número único de factura', max_length=50, unique=True, verbose_name='Número de Factura')),
                ('cliente_nombre', models.CharField(blank=True, help_text='Para ventas al contado sin cliente registrado', max_length=200, null=True, verbose_name='Nombre del Cliente (si no está registrado)')),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Venta')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal (C$)')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento (C$)')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total (C$)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='COMPLETADA', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente puede ser null para ventas al contado sin registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='ventas.cliente', verbose_name='Cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_vendidas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_venta', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio al momento de la venta', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario (C$)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal (C$)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='inventario.producto', verbose_name='Producto')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Facturas',
            },
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero_factura'], name='ventas_fact_numero__b8c200_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha_venta'], name='ventas_fact_fecha_v_e63c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado'], name='ventas_fact_estado_a26c96_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['vendedor'], name='ventas_fact_vendedo_b6ce6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detallefactura',
            unique_together={('factura', 'producto')},
        ),
    ]
